
lista_colunas = [
    "Nome Executor",
    "Titulo Objeto",
    "Detalhamento Objeto",
    "Objetivo Principal",
    "Composicao Objeto",
    "Tipo Intervencao",
    "Tipo Obra",
    "Meta Fisica",
    "Unidade Medida",
    "Novo PAC",
    "ID Novo PAC",
    "Modalidade",
    "Normativo Principal",
    "Regime Simplificado",
    "Numero Instrumento",
    "SIAFI",
    "Numero Proposta",
    "Status Instrumento",
    "Status Complementar",
    "Providencias",
    "Data Previdencias",
    "Restricoes",
    "Resultados",
    "Estagio Objeto",
    "Execucao Fisica",
    "Detalhamento Execucao",
    "Motivo Paralisacao",
    "Status Funcionalidade",
    "Execucao Adequada PT",
    "Descricao Problemas",
    "Data Referencia Execucao",
    "Fonte Informacao Execucao",
    "Previsao Inicio",
    "Previsao Termino",
    "Inicio Objeto",
    "Referencia Inicio",
    "Termino Objeto",
    "Referencia Termino",
    "Inauguracao Objeto",
    "Data Recebimento Definitivo",
    "Visita Preliminar",
    "Visita Final",
    "Unidade Departamento",
    "Analista",
    "Data Assinatura",
    "Data Publicacao",
    "Inicio Vigencia",
    "Fim Vigencia Atual",
    "Fim Vigencia Atual (dias)",
    "Fim Vigencia Original",
    "Valor Total Inicial",
    "Valor Total Atual",
    "Repasse Previsto Inicial",
    "Repasse Previsto Atual",
    "Contrapartida Inicial",
    "Contrapartida Atual",
    "Valor Referencia Repasse",
    "Total Empenhado",
    "Valor a Empenhar",
    "Total Repassado",
    "Valor a Repassar",
    "Total Aprovado Repasse",
    "Saldo Empenho",
    "Saldo Aprovado Repasse",
    "Valor Aporte Adicional",
    "Descricao Aporte Adicional",
    "Ano",
    "Programa",
    "Acao_Ultima",
    "Municipios Beneficiados",
    "Qtd Municipios",
    "Populacao Beneficiada",
    "Descricao Beneficios",
    "Latitude",
    "Longitude",
    "PI 130 2013",
    "Prazo Suspensiva Original",
    "Prazo Suspensiva Vigente",
    "Data Abertura Processo",
    "Data Apresentacao Proposta",
    "Data Retirada Suspensiva",
    "Data Inicio Supervisao",
    "Data Analise PCF",
    "DOH",
    "Ativo"
]

lista_colunas_min = [
    "nome_executor",
    "titulo_objeto",
    "detalhamento_objeto",
    "objetivo_principal",
    "composicao_objeto",
    "tipo_intervencao",
    "tipo_obra",
    "meta_fisica", ###
    "unidade_medida",
    "novo_pac",
    "id_novo_pac",
    "modalidade",
    "normativo_principal",
    "regime_simplificado",
    "numero_instrumento",
    "siafi",
    "numero_proposta",
    "status_instrumento",
    "status_complementar",
    "providencias",
    "data_previdencias",
    "restricoes",
    "resultados",
    "estagio_objeto",
    "execucao_fisica",
    "detalhamento_execucao",
    "motivo_paralisacao",
    "status_funcionalidade",
    "execucao_adequada_pt",
    "descricao_problemas",
    "data_referencia_execucao",
    "fonte_informacao_execucao",
    "previsao_inicio",
    "previsao_termino",
    "inicio_objeto",
    "referencia_inicio",
    "termino_objeto",
    "referencia_termino",
    "inauguracao_objeto",
    "data_recebimento_definitivo",
    "visita_preliminar",
    "visita_final",
    "unidade_departamento",
    "analista",
    "data_assinatura",
    "data_publicacao",
    "inicio_vigencia",
    "fim_vigencia_atual",
    "fim_vigencia_atual_(dias)",
    "fim_vigencia_original",
    "valor_total_inicial",
    "valor_total_atual",
    "repasse_previsto_inicial",
    "repasse_previsto_atual",
    "contrapartida_inicial",
    "contrapartida_atual",
    "valor_referencia_repasse",
    "total_empenhado",
    "valor_a_empenhar",
    "total_repassado",
    "valor_a_repassar",
    "total_aprovado_repasse",
    "saldo_empenho",
    "saldo_aprovado_repasse",
    "valor_aporte_adicional",
    "descricao_aporte_adicional",
    "ano",
    "programa",
    "acao_ultima",
    "municipios_beneficiados",
    "qtd_municipios",
    "populacao_beneficiada",
    "descricao_beneficios",
    "latitude",
    "longitude",
    "pi_130_2013",
    "prazo_suspensiva_original",
    "prazo_suspensiva_vigente",
    "data_abertura_processo",
    "data_apresentacao_proposta",
    "data_retirada_suspensiva",
    "data_inicio_supervisao",
    "data_analise_pcf",
    "doh",
    "ativo"
]


# print("Tamanho lista_colunas", len(lista_colunas))
# print("Tamanho lista_colunas_min", len(lista_colunas_min))
for i, (valor, func) in enumerate(zip(lista_colunas, lista_colunas_min)):
    print(
        f'            elif column_names[i] == "{valor}":',
        f'\n              Button(content_frame, text="Adicionar ao relatório", command=lambda v=val: adicionar_{func}(v)).grid(row=i, column=2, padx=10, pady=5)'
    )


# elif column_names[i] == "UF":
#                 Button(content_frame,
#                     text="Adicionar ao relatório",
#                     command=lambda v=val: adicionar_uf(v)
#                     ).grid(row=i, column=2, padx=10, pady=5)