
# Lista das colunas da planilha excel em minúsculo e com "_"
lista_colunas = [
    "nome_executor",
    "titulo_objeto",
    "detalhamento_objeto",
    "objetivo_principal",
    "composicao_objeto",
    "tipo_intervencao",
    "tipo_obra",
    "meta_fisica", ###
    "unidade_medida",
    "novo_pac",
    "id_novo_pac",
    "modalidade",
    "normativo_principal",
    "regime_simplificado",
    "numero_instrumento",
    "siafi",
    "numero_proposta",
    "status_instrumento",
    "status_complementar",
    "providencias",
    "data_previdencias",
    "restricoes",
    "resultados",
    "estagio_objeto",
    "execucao_fisica",
    "detalhamento_execucao",
    "motivo_paralisacao",
    "status_funcionalidade",
    "execucao_adequada_pt",
    "descricao_problemas",
    "data_referencia_execucao",
    "fonte_informacao_execucao",
    "previsao_inicio",
    "previsao_termino",
    "inicio_objeto",
    "referencia_inicio",
    "termino_objeto",
    "referencia_termino",
    "inauguracao_objeto",
    "data_recebimento_definitivo",
    "visita_preliminar",
    "visita_final",
    "unidade_departamento",
    "analista",
    "data_assinatura",
    "data_publicacao",
    "inicio_vigencia",
    "fim_vigencia_atual",
    "fim_vigencia_atual_(dias)",
    "fim_vigencia_original",
    "valor_total_inicial",
    "valor_total_atual",
    "repasse_previsto_inicial",
    "repasse_previsto_atual",
    "contrapartida_inicial",
    "contrapartida_atual",
    "valor_referencia_repasse",
    "total_empenhado",
    "valor_a_empenhar",
    "total_repassado",
    "valor_a_repassar",
    "total_aprovado_repasse",
    "saldo_empenho",
    "saldo_aprovado_repasse",
    "valor_aporte_adicional",
    "descricao_aporte_adicional",
    "ano",
    "programa",
    "acao_ultima",
    "municipios_beneficiados",
    "qtd_municipios",
    "populacao_beneficiada",
    "descricao_beneficios",
    "latitude",
    "longitude",
    "pi_130_2013",
    "prazo_suspensiva_original",
    "prazo_suspensiva_vigente",
    "data_abertura_processo",
    "data_apresentacao_proposta",
    "data_retirada_suspensiva",
    "data_inicio_supervisao",
    "data_analise_pcf",
    "doh",
    "ativo"
]


# lista_colunas = [
#     "Processo",
#     "UF",
#     "Tipo Convenente",
#     "Nome Convenente",
#     "Nome Executor",
#     "Titulo Objeto",
#     "Detalhamento Objeto",
#     "Objetivo Principal",
#     "Composicao Objeto",
#     "Tipo Intervencao",
#     "Tipo Obra",
#     "Meta Fisica",
#     "Unidade Medida",
#     "Novo PAC",
#     "ID Novo PAC",
#     "Modalidade",
#     "Normativo Principal",
#     "Regime Simplificado",
#     "Numero Instrumento",
#     "SIAFI",
#     "Numero Proposta",
#     "Status Instrumento",
#     "Status Complementar",
#     "Providencias",
#     "Data Previdencias",
#     "Restricoes",
#     "Resultados",
#     "Estagio Objeto",
#     "Execucao Fisica",
#     "Detalhamento Execucao",
#     "Motivo Paralisacao",
#     "Status Funcionalidade",
#     "Execucao Adequada PT",
#     "Descricao Problemas",
#     "Data Referencia Execucao",
#     "Fonte Informacao Execucao",
#     "Previsao Inicio",
#     "Previsao Termino",
#     "Inicio Objeto",
#     "Referencia Inicio",
#     "Termino Objeto",
#     "Referencia Termino",
#     "Inauguracao Objeto",
#     "Data Recebimento Definitivo",
#     "Visita Preliminar",
#     "Visita Final",
#     "Unidade Departamento",
#     "Analista",
#     "Data Assinatura",
#     "Data Publicacao",
#     "Inicio Vigencia",
#     "Fim Vigencia Atual",
#     "Fim Vigencia Atual (dias)",
#     "Fim Vigencia Original",
#     "Valor Total Inicial",
#     "Valor Total Atual",
#     "Repasse Previsto Inicial",
#     "Repasse Previsto Atual",
#     "Contrapartida Inicial",
#     "Contrapartida Atual",
#     "Valor Referencia Repasse",
#     "Total Empenhado",
#     "Valor a Empenhar",
#     "Total Repassado",
#     "Valor a Repassar",
#     "Total Aprovado Repasse",
#     "Saldo Empenho",
#     "Saldo Aprovado Repasse",
#     "Valor Aporte Adicional",
#     "Descricao Aporte Adicional",
#     "Ano",
#     "Programa",
#     "Acao_Ultima",
#     "Municipios Beneficiados",
#     "Qtd Municipios",
#     "Populacao Beneficiada",
#     "Descricao Beneficios",
#     "Latitude",
#     "Longitude",
#     "PI 130 2013",
#     "Prazo Suspensiva Original",
#     "Prazo Suspensiva Vigente",
#     "Data Abertura Processo",
#     "Data Apresentacao Proposta",
#     "Data Retirada Suspensiva",
#     "Data Inicio Supervisao",
#     "Data Analise PCF",
#     "DOH",
#     "Ativo"
# ]

print("Numero de itens da lista: ", len(lista_colunas))
# for valor in lista_colunas:
#     print(f"def adicionar_{valor}(v):\n",   
#           f"    global {valor}\n",
#           f"    {valor} = v\n",
#           f"    nome_documento = 'teste_funcao.docx'\n",
#           "    caminho_template = 'C:\\\\Users\\\\walyson.ferreira\\\\Desktop\\\\openpy\\\\template\\\\template.docx'\n",
#           "    doc = DocxTemplate(caminho_template)\n",
#           "    if 'context' not in globals():\n",
#           "        global context\n",
#           "        context = {}\n",
#           f"    context['{valor}'] = {valor}\n",
#           "    doc.render(context)\n",
#           "    doc.save(nome_documento)\n")

# with open("funcoes_adicionar.py", "w", encoding="utf-8") as f:
#     f.write("from docxtpl import DocxTemplate\n\n")
#     for valor in lista_colunas:
#         f.write(f"def adicionar_{valor}(v):\n")
#         f.write(f"    global {valor}\n")
#         f.write(f"    {valor} = v\n")
#         f.write("    nome_documento = 'teste_funcao.docx'\n")
#         f.write("    caminho_template = 'C:\\\\Users\\\\walyson.ferreira\\\\Desktop\\\\openpy\\\\template\\\\template.docx'\n")
#         f.write("    doc = DocxTemplate(caminho_template)\n")
#         f.write("    if 'context' not in globals():\n")
#         f.write("        global context\n")
#         f.write("        context = {}\n")
#         f.write(f"    context['{valor}'] = {valor}\n")
#         f.write("    doc.render(context)\n")
#         f.write("    doc.save(nome_documento)\n\n")